packages:
  - "."

overrides:
  vite: 6.4.3

onlyBuiltDependencies:
  - esbuild
  - "@tailwindcss/oxide"

allowBuilds:
  '@tailwindcss/oxide': set this to true or false
  esbuild: set this to true or false
