/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pujzeomddvquxeacblvr"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1anplb21kZHZxdXhlYWNibHZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODUyNDUzMzIsImV4cCI6MjEwMDgyMTMzMn0.nore-Sivs5AGQFFYUIxlzWmiQlFd_tz-daXnjVZIhng"