const fs = require('fs');

const content = `# Release Process & Evidence

This document defines the automated release process and the requirements for the \`release-evidence.yaml\` artifact.

Issue Tracking Statuses:
- \`planned\`
- \`implemented_unverified\`
- \`verified_in_ci\`
- \`verified_in_staging\`
- \`released\`
(Do not use a generic "Fixed" status).

## 1. Release Evidence Artifact
**Rule: CI MUST NOT modify markdown files in the repository to record release evidence.**
Instead, CI MUST automatically generate an immutable artifact named \`release-evidence.yaml\` and attach it to the GitHub Release or Deployment Attestation.

The artifact must be tied to the exact commit and signed. Production must only promote the exact artifact that passed staging.

Example \`release-evidence.yaml\`:
\`\`\`yaml
release:
  commit_sha: "c4b3a..."
  ci_run_id: "123456789"
  frontend_deployment_id: "dep_123"
  edge_deployment_id: "edge_456"
  artifact_sha256: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
  migration_checksums:
    - file: "20260816000000_phase38_round_tickets_state.sql"
      sha256: "..."
  integration_tests: "pass"
  staging_verified_at: "2026-08-17T12:00:00Z"
  restore_drill_result: "pass"
  approved_by: "github_actions_bot"
\`\`\`

## 2. Release Gates
[ ] Release artifact \`release-evidence.yaml\` is securely generated by CI.
[ ] Migrations run successfully on a clean DB and anonymized production snapshot.
[ ] Migration checksums are identical between staging and production.
[ ] Version pinning test: V1 tickets submit correctly after V2 deployment.
[ ] Rolling deployment test: N and N+1 instances process living tickets.
[ ] Rule-set/config canonical hash and mutation test pass.
[ ] Offline schema N, N-1, N-2 pass; N-3 correctly routed to dead-letter.
[ ] Direct guest-upgrade RPC rejected for normal users.
[ ] XFF spoof, RLS negative, admin step-up, and old-token tests pass.
[ ] Retention cron and export manifest strictly match privacy policy.
[ ] Dashboard SQL successfully runs on staging schema.
[ ] Restore drill reports actual RPO/RTO and valid checksums.
[ ] Canary production meets SLO/error budget.
[ ] Roll-forward compatibility confirmed.
`;

fs.writeFileSync('docs/release-process.md', content);
console.log("Done M1");
